#!/bin/bash

. $(dirname "$0")/emergency-settings


THRESHOLD=$(( ${1:-$EMERGENCY_TRESHOLD}*2 ))

STDIN=$(cat -)
echo -n "$STDIN"

MAILQ=$(mailq | wc -l)

if [[ $MAILQ -gt $THRESHOLD ]]; then
    python -c "$(cat <<- EOF
		import smtplib
		import email.utils
		from email.mime.text import MIMEText
		
		MAIL_FROM = '$EMERGENCY_MAIL_FROM'
		SUBJECT = 'EMERGENCY MAIL ABUSE REPORT - $EMERGENCY_SERVER_NAME'
		MESSAGE = """$STDIN"""
		
		for SMTP_SERVER, MAIL_TO in $EMERGENCY_MAIL_TO:
		    msg = MIMEText(MESSAGE)
		    msg['To'] = ', '.join(MAIL_TO)
		    msg['From'] = MAIL_FROM
		    msg['Subject'] = SUBJECT
		    server = smtplib.SMTP(SMTP_SERVER, 25)
		    try:
		        server.ehlo()
		        server.starttls()
		        server.ehlo()
		        server.sendmail(MAIL_FROM, MAIL_TO, msg.as_string())
		    except Exception as detail:
		        print 'Error sending:', detail
		        continue
		    finally:
		        server.quit()
		
		EOF
    )"
fi
