#!/bin/bash

# USAGE:
#   find /home/ -mtime -2 -iname "*php" | php-shell-scan [QUARANTINE_DIR]


QUARANTINE_DIR=${1:-"/root/shells/"}

[[ ! -e "$QUARANTINE_DIR" ]] && mkdir "$QUARANTINE_DIR"


TMP_FILE=$(mktemp)
SHELLS_TIME=$(date +%s)
while read filename; do
    # Lookup for common php shell patterns
    if [[ $(egrep "(@error_reporting\(0\); @ini_set\('error_log',NULL\); @ini_set\('log_errors',0\);|7X1re9s2z/Dn9VcwmjfZq\+PYTtu7s2MnaQ5t2jTpcugp6ePJsmxrkS1PkuNkWf77C4C)" "$filename" 2> /dev/null) ]]; then
        mv "$filename" "$QUARANTINE_DIR"
        echo "${filename} [COMMON]"
    elif [[ $(grep '$x74\[41\].$x74\[71\].$x74\[10\].$x74\[96\].$x74\[12\].$x' "$filename" 2> /dev/null) ]]; then
        mv "$filename" "$QUARANTINE_DIR"
        echo "${filename} [COMMON]"
    else
        # Cleanup possible backdoors
        if [[ $(grep '<?php\s*eval\s*(\s*base64_decode\s*(\s*$_POST\['"'"'[0-z]*'"'"'\]));?>' "$filename" 2> /dev/null) ]]; then
            sed -i 's/<?php\s*eval\s*(\s*base64_decode\s*(\s*$_POST\['"'"'[0-z]*'"'"'\]));?>//g' "$filename" 2> /dev/null
            echo "${filename} [BACKDOOR]"
    elif [[ $(grep 'eval\s*(\s*base64_decode.*_POST' "$filename" 2> /dev/null) ]]; then
            echo "${filename} [NON-CLEANED BACKDOOR]"
        fi
        if [[ "$filename" != "" ]]; then
            echo "$filename" >> "$TMP_FILE"
        fi
    fi;
done


CLAM_TIME=$(date +%s)
REMOVED=""
if [[ -s "$TMP_FILE" ]]; then
    # clamscan is not able to read a list of files from stdin, WTF!
    while read filename; do
        mv "$filename" "$QUARANTINE_DIR"
        echo "${filename} [CLAMSCAN]"
        REMOVED="${REMOVED}\n${filename}"
    done < <(clamscan -i -f "$TMP_FILE" 2>&1 | grep FOUND | cut -d':' -f1)
fi


DETECTOR_TIME=$(date +%s)
echo "$REMOVED"| grep -v -x -f - "$TMP_FILE"
while read line; do
    FILENAME=$(echo "$line" | awk {'print $1'})
    if [[ $(echo "$line" | grep ' INFECTED-FILE$') ]]; then
        echo "${FILENAME} [NON-CLEANED BACKDOOR]"
    else
        mv "$FILENAME" "$QUARANTINE_DIR"
        echo "$FILENAME [DETECTOR]"
    fi
done < <(cat "$TMP_FILE" | $(dirname $0)/php-shell-detector)


rm -f "$TMP_FILE"

if [[ "$SHELLS" ]]; then
    SHELLS_TIME=$(($(date +%s) - $SHELLS_TIME))
    CLAM_TIME=$(($(date +%s) - $CLAM_TIME))
    DETECTOR_TIME=$(($(date +%s) - $DETECTOR_TIME))
    echo -e "$SHELLS"
    echo -e "\n--------------------------"
    echo "SHELLS TIME: $SHELLS_TIME seconds"
    echo "CLAM TIME: $CLAM_TIME seconds"
    echo "DETECTOR TIME: $DETECTOR_TIME seconds"
    echo "TOTAL TIME: $(($CLAM_TIME+$SHELLS_TIME+$DETECTOR_TIME)) seconds"
    exit 1
fi


exit 0
