#!/bin/bash

# USAGE:
#   bash postfix-spam-scan PERIOD MAX_CONNECTIONS
# TODO bash postfix-spam-scan PERIOD -w MAX_CONNECTIONS,MAX_NETS,MAX_UNKNOWNS -d MAX_CONNECTIONS,MAX_NETS,MAX_UNKNOWNS


PERIOD=${1:-'1hour'}
MAX_CONNECTIONS=${2:-90}


log=$(
    grep "sasl_username=" /var/log/mail.log | awk '$0>=from&&$0<=to' \
    from="$(date +%b" "%d" "%H:%M:%S -d -$PERIOD | sed 's/ 0\([0-9]\) /  \1 /')" \
    to="$(date +%b" "%d" "%H:%M:%S | sed 's/ 0\([0-9]\) /  \1 /')" \
)

period=$(echo $PERIOD | sed "s/\([0-9]*\)/\1 /")
message="During the last $period the following senders have made at least $MAX_CONNECTIONS SMTP connections."
sent=false

while read line; do
    current=($(echo "$line"))
    if [[ ${current[0]} != "" && ${current[0]} -ge $MAX_CONNECTIONS ]]; then
        userlogs=$(echo "$log" | grep "sasl_username=${current[1]}")
        logentry=$(echo "$userlogs" | head -n1)
        numips=$(echo "$userlogs" | cut -d'[' -f3 | cut -d']' -f1 | sort | uniq | wc -l)
        unknown=$(echo "$userlogs" | grep 'client=unknown\[' | cut -d'[' -f3 | cut -d']' -f1 | sort | uniq | wc -l)
        nets=$(echo "$userlogs" | cut -d'[' -f2 | cut -d'=' -f2 | sed "s/.*[0-9].//" | sort | uniq | wc -l)
        [ $sent = false ] && echo -e "${message}\n" && sent=true
        echo "${current[0]} (${nets} nets/${unknown} unknown/${numips} IPs) -- ${logentry}"
    fi;
done < <(echo "$log" | cut -d'=' -f4 | sort -n | uniq -c)
