#!/bin/bash

# USAGE:
#   exim-spam-scan SECONDS DEFAULT_MAX_CONNECTIONS

SECONDS=${1:-3600}
DEFAULT=${2:-60}


log=$(grep '<=' /var/log/exim4/mainlog | awk -v SECONDS=$SECONDS '
    BEGIN {
        now = systime()
        current = strftime("%y:%m:%d:%H:%m:%S", now)
        boundary = SECONDS
    } {
        column1 = $1
        column2 = $2
        split(column1, d, "-")
        split(column2, t, ":")
        logtime = sprintf("%s %s %s %s %s %s", d[1], d[2], d[3], t[1], t[2], t[3])
        log_entry_time = mktime(logtime)
        if ( now - log_entry_time <= boundary ){
            print $0
        }
    }'
)


period="$SECONDS seconds"
message="During the last $period the following senders have made at least $DEFAULT SMTP connections."
sent=false
declare -A max_conn
overrides="$(dirname $(readlink -f "$0"))/exim-spam-scan.overrides"

if [[ -e "${overrides}" ]]; then
    while read line; do
        if [[ "${line}" != "" ]]; then
            line=( ${line} )
            max_conn[${line[0]}]=${line[1]}
        fi
    done < <(cat ${overrides})
fi


# USER based P=local
while read line; do
    line=( ${line} )
    conn=${line[0]}
    user=${line[1]}
    if [[ ${conn} -gt ${max_conn[$user]:-$DEFAULT} ]]; then
        if [[ $sent = false ]]; then
            echo -e "${message}\n"
            sent=true
        fi
        logentry=$(echo "$log" | grep "U=${user} "|head -n1)
        echo "${conn} -- ${logentry}"
    fi;
done < <(echo "$log" | grep 'U=' | awk -F'U=' {'print $2'} | awk {'print $1'} | sort | uniq -c)


# HOST based P=smtp
while read line; do
    line=( ${line} )
    conn=${line[0]}
    user=${line[1]}
    if [[ ${conn} -gt ${max_conn[$user]:-$DEFAULT} ]]; then
        if [[ $sent = false ]]; then
            echo -e "${message}\n"
            sent=true
        fi
        logentry=$(echo "$log" | grep "\(${user}\)" | head -n1)
        echo "${conn} -- ${logentry}"
    fi;
done < <(echo "$log" | grep -v 'U=' | awk -F'(' {'print $2'} | cut -d')' -f1 | sort | uniq -c)
